name: Tests

on:
  push:
    branches:
      - "**"

jobs:
  lint:
    if: contains(github.event.head_commit.message, '[github-actions]')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run SCons checker
        run: python .github/check_sconscripts.py

      - name: Lint Python files (excluding source/lib)
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Run pylint
        run: |
          python -m pip install --upgrade pip pylint
          find . -type f -name "*.py" ! -path "./source/lib/*" -print0 \
            | xargs -0 pylint --rcfile=source/lib/linter_config/.pylintrc
