name: Tests

on:
  push:
    branches:
      - "**"

jobs:
  lint:
    if: contains(github.event.head_commit.message, '[github-actions]')
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Configure JMSLab Github Actions Bot
        run: |
          git config --global user.name "GitHub Actions [bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"


      - id: scons
        name: Run SCons checker
        continue-on-error: true
        run: python .github/check_sconscripts.py

      - id: newlines
        name: Add newlines when needed
        continue-on-error: true
        run: python .github/add_newlines.py --fix yes

      - id: commit_newlines
        name: Commit newline fixes (if any)
        if: ${{ always() }}
        run: |
          if [ -f .github/newlines_to_commit.txt ] && [ -s .github/newlines_to_commit.txt ]; then
            echo "Files to commit:"
            cat .github/newlines_to_commit.txt
            git add $(cat .github/newlines_to_commit.txt)
            if git diff --staged --quiet; then
              echo "No staged changes to commit."
            else
              git commit -m "[github-actions] Add missing newlines" --no-verify
              git push
            fi
          else
            echo "No newline fixes to commit."
          fi

      - id: scons_log
        name: Check for failed scons builds
        continue-on-error: false
        run: python .github/check_sconscript_log.py
